title: Aniket's Blog
description: "My journey through Advanced Placement Computer Science from August 2023 to June 2024"
owner_name: Aniket Chakradeo
github_username: AniCricKet
baseurl: "/musical-guacamole"

# remote_theme: pages-themes/dinky@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
future: true
